### ISSUE TITLE
ssh.sh plugin not working

### ISSUE THREAD

**Issue by C4Wiz** [matryer/xbar-plugins#1579]
list populates from ~/.ssh/config but when clicked nothing happens!

```
#!/usr/bin/env bash
#
# Quickly SSH to your favorite hosts
# The list of hosts are extracted from ~/.ssh/config
#
# <xbar.title>SSH</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Thameera Senanayaka</xbar.author>
# <xbar.author.github>thameera</xbar.author.github>
# <xbar.desc>Quickly SSH to your favorite hosts listed in your ~/.ssh/config file</xbar.desc>
#

echo "ssh"
echo "---"
awk  '/^Host / && !/\*/ {print $2" | bash=ssh param1="$2}' ~/.ssh/config
```

**Comment by derd3000** [comment]
Running into the same issue :(

**Comment by C4Wiz** [comment]
anyone?

**Comment by LivelyCarpet87** [comment]
I'm not sure if this is going to be helpful, but I have seen similar issues with the BETA release of xbar. I've noticed occasionally xbar crashes and none of the buttons in plugins work. It generally is fixed when I restart xbar. Is this phenomenon specific to this plugin?

**Comment by lukestein** [comment]
Can you confirm that xbar has the needed system privacy preferences to run commands in Terminal? It should have asked at first install, but if it didn't—or if you didn't say yes—you may run into these problems.

More details on privacy preferences (and hints towards a potential solution) [here](https://github.com/swiftbar/SwiftBar/discussions/189#discussioncomment-641930).

**Comment by C4Wiz** [comment]
> Can you confirm that xbar has the needed system privacy preferences to run commands in Terminal? It should have asked at first install, but if it didn't—or if you didn't say yes—you may run into these problems.
> 
> More details on privacy preferences (and hints towards a potential solution) [here](https://github.com/swiftbar/SwiftBar/discussions/189#discussioncomment-641930).

i can confirm i have the required preferences, but it still does not work!

<img width="189" alt="Screen Shot 2021-04-23 at 7 33 05 AM" src="https://user-images.githubusercontent.com/3883521/115868802-fe6b3880-a40a-11eb-9e69-b6ea7bca57af.png">
<img width="260" alt="Screen Shot 2021-04-23 at 7 57 38 AM" src="https://user-images.githubusercontent.com/3883521/115868827-05924680-a40b-11eb-99d6-586b76809200.png">

**Comment by lukestein** [comment]
This issue with `ssh.sh` appears to be an example of the more general bug documented in #680 : Whether the `terminal` parameter is true, false, or missing, commands do not run in the terminal

**Comment by matryer** [comment]
Please try with the latest release, we fixed `terminal=true`.
